name: Tests

on:
  push:
    branches: [ main, cgi ]
  pull_request:
    branches: [ main, cgi ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installation
      run: sudo apt update && sudo apt install -y netcat make valgrind
    - name: Tests
      run: make test
